spring:
  main:
    lazy-initialization: true
  config:
    activate:
      on-profile:

apis:
  pokeapi:
    uriTemplate: ${POKEAPI_URL:https://pokeapi.co/api/v2/pokemon}
    uriTemplateWithId: ${POKEAPI_WITH_ID_URL:https://pokeapi.co/api/v2/pokemon/{id}}

server:
  port: ${PORT:8080}
  address: ${APP_ADDRESS:0.0.0.0}
  error:
    include-message: always
  undertow:
    no-request-timeout: -1